server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://xmbkkicgihbdul:30d5d312ec3933776463a943c67361a95b77e7eadd3b1c236204d907153626a2@ec2-3-233-7-12.compute-1.amazonaws.com:5432/da3305vshuk04i
    username: xmbkkicgihbdul
    password: 30d5d312ec3933776463a943c67361a95b77e7eadd3b1c236204d907153626a2
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      dbl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: BETA 0.0.1